//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport.BDModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIP_Ves
    {
        public int id_izn_ves { get; set; }
        public string ves { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int id_pol { get; set; }
    
        public virtual DIP_Polzovatel DIP_Polzovatel { get; set; }
    }
}
