//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport.BDModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIP_Polzovatel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DIP_Polzovatel()
        {
            this.DIP_Dieta = new HashSet<DIP_Dieta>();
            this.DIP_Programma = new HashSet<DIP_Programma>();
            this.DIP_Ves = new HashSet<DIP_Ves>();
        }
    
        public int ID_Polzovatel { get; set; }
        public int ID_roli { get; set; }
        public string Imya { get; set; }
        public string Familiya { get; set; }
        public string Othestvo { get; set; }
        public System.DateTime Data_Rojdeniya { get; set; }
        public string email { get; set; }
        public int Rost { get; set; }
        public string login { get; set; }
        public string Parol { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIP_Dieta> DIP_Dieta { get; set; }
        public virtual DIP_Rol DIP_Rol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIP_Programma> DIP_Programma { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DIP_Ves> DIP_Ves { get; set; }
    }
}
