//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport.BDModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DIP_Dieta
    {
        public int id_Diety { get; set; }
        public int id_Blyda { get; set; }
        public int id_Vremya { get; set; }
        public string nazvanie { get; set; }
        public string razmer_porcii { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> id_pol { get; set; }
    
        public virtual DIP_Blyado DIP_Blyado { get; set; }
        public virtual DIP_Polzovatel DIP_Polzovatel { get; set; }
        public virtual DIP_Vremya DIP_Vremya { get; set; }
    }
}
