//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sport.BDModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user45_dbEntities4 : DbContext
    {
        public user45_dbEntities4()
            : base("name=user45_dbEntities4")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DIP_Blyado> DIP_Blyado { get; set; }
        public virtual DbSet<DIP_Dieta> DIP_Dieta { get; set; }
        public virtual DbSet<DIP_DN> DIP_DN { get; set; }
        public virtual DbSet<DIP_Kyrs> DIP_Kyrs { get; set; }
        public virtual DbSet<DIP_Polzovatel> DIP_Polzovatel { get; set; }
        public virtual DbSet<DIP_Programma> DIP_Programma { get; set; }
        public virtual DbSet<DIP_Rol> DIP_Rol { get; set; }
        public virtual DbSet<DIP_Ves> DIP_Ves { get; set; }
        public virtual DbSet<DIP_Vremya> DIP_Vremya { get; set; }
    }
}
